spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    app: micro-java
    provider: jkube
    group: com.redhat.training.openshift.hello
  strategy:
    rollingParams:
      timeoutSeconds: 3600
    type: Rolling
  template:
    metadata:
      labels:
        app: micro-java
        provider: jkube
        version: 1.0
        group: com.redhat.training.openshift.hello
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
          - configMapRef:
              name: configmap-hello
        image: micro-java:1.0
        imagePullPolicy: IfNotPresent
        name: quarkus
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
