spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    app: micro-java
    provider: jkube
    group: com.redhat.training.openshift.hello
  strategy:
    rollingParams:
      timeoutSeconds: 3600
    type: Rolling
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-ref: master
        jkube.io/git-url: git@github.com:maudemor/DO288-apps.git
        app.openshift.io/vcs-uri: git@github.com:maudemor/DO288-apps.git
        jkube.io/git-commit: 3bffad109a77ebd72831d8f791c38df68db28e60
        jkube.io/git-branch: master
      labels:
        app: micro-java
        provider: jkube
        version: 1.0.0-SNAPSHOT
        group: com.redhat.training.openshift.hello
    spec:
      containers:
      - envFrom:
          - configMapRef:
              name: configmap-hello
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: micro-java:latest
        imagePullPolicy: IfNotPresent
        name: quarkus
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
